# Site settings
title: No Smartphone
tagline: La cancellazione dei tempi morti
url: http://homobruno.github.io/no-smartphone/ # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
github: homobruno

# Use this for production :compressed
sass:
    sass_dir: _sass

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
